// <auto-generated />
using IO.Swagger;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IO.Swagger.Migrations
{
    [DbContext(typeof(MappingContext))]
    partial class MappingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:btree_gin", "'btree_gin', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:btree_gist", "'btree_gist', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:citext", "'citext', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:cube", "'cube', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:dblink", "'dblink', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:dict_int", "'dict_int', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:dict_xsyn", "'dict_xsyn', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:earthdistance", "'earthdistance', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:fuzzystrmatch", "'fuzzystrmatch', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:hstore", "'hstore', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:intarray", "'intarray', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:ltree", "'ltree', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:pg_stat_statements", "'pg_stat_statements', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:pg_trgm", "'pg_trgm', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:pgcrypto", "'pgcrypto', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:pgrowlocks", "'pgrowlocks', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:pgstattuple", "'pgstattuple', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:plv8", "'plv8', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:tablefunc", "'tablefunc', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:unaccent", "'unaccent', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", "'uuid-ossp', '', ''")
                .HasAnnotation("Npgsql:PostgresExtension:xml2", "'xml2', '', ''")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("IO.Swagger.Database.MapPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.HasKey("Id");

                    b.ToTable("MapPoints");
                });

            modelBuilder.Entity("IO.Swagger.Database.MetaData", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<Guid?>("MapPointId");

                    b.Property<string>("Value");

                    b.HasKey("ID");

                    b.HasIndex("MapPointId");

                    b.ToTable("MetaData");
                });

            modelBuilder.Entity("IO.Swagger.Database.MetaData", b =>
                {
                    b.HasOne("IO.Swagger.Database.MapPoint", "MapPoint")
                        .WithMany("MetaData")
                        .HasForeignKey("MapPointId");
                });
#pragma warning restore 612, 618
        }
    }
}
